### ISSUE TITLE
Dead link in readme

### ISSUE THREAD

**Issue by SharkBeard** [BrandonJoyce356/dotfiles#1]
Readme leads to a dead link. Recommend [Article about using stow](http://brandon.invergo.net/news/2012-05-26-using-gnu-stow-to-manage-your-dotfiles.html) or [Article with less detail but includes installing stow](https://turanct.wordpress.com/2013/09/12/track-your-dotfiles-and-homedir-configurations-in-git-using-gnu-stow/)

**Comment by brandonjoyce** [comment]
Fixed! Thanks.
